# ElementMeteor
# Версия: 1.0

config-version: 1

settings:
  locale: "ru_RU"  # локализация: ru_RU или en_US

database:
  host: localhost
  port: 3306
  name: elementmeteor
  username: root
  password: "default_encrypted_password"

# Настройки абилити
ability:
  # Время ожидания между использованиями (в миллисекундах, 5000 = 5 секунд)
  cooldown: 5000
  
  # Максимальное расстояние, которое может преодолеть метеор (в блоках)
  range: 100.0
  
  # Скорость движения метеора (блоков за тик)
  speed: 1.2
  
  # Урон, наносимый взрывом метеорита
  damage: 5.0
  
  # Базовый радиус взрыва на количество использований
  base-radius: 2.0
  
  # Максимальный дополнительный радиус
  max-additional-radius: 3.0
  
  # Настройки анимации восстановления
  restoration:
    # Задержка перед началом восстановления (в секундах)
    delay: 4
    # Скорость волн восстановления (тики)
    wave-speed: 3
    # Включить эффекты восстановления
    effects: true

# Сообщения
messages:
  prefix: "&6[ElementMeteor] &r"
  no-bending-player: "&cОшибка: Игрок не найден в системе"
  ability-given: "&6Вы получили способность &cМетеор&6!"
  ability-used: "&6Вы запустили метеор!"
  ability-item-name: "Метеорная способность"
  ability-item-description: "ЛКМ - запустить метеор"
  command-player-only: "&cЭту команду могут использовать только игроки!"
  command-no-permission: "&cУ вас нет прав на использование этой команды!"
  menu-error: "&cПроизошла ошибка при открытии меню!"
  wrong-element: "&cВы не можете взять метеор пока у вас установлен другой элемент! Установите элемент &6Fire &cчерез &e/bending choose Fire"
  no-element: "&cУ вас не выбран элемент! Выберите элемент &6Fire &cчерез &e/bending choose Fire"
  ability-already-exists: "&cУ вас уже есть способность &6Метеор &cв инвентаре!"
